title: Markus Rothe
email: mr@markusrothe.dev
description: Description
url: https://www.markusrothe.dev # the base hostname & protocol for your site, e.g. http://example.com

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/avatar.png # logo visible in the topbar
excerpt_separator: <!-- more -->

menu:
    - title: 'Home'
      url: '/'
    
    - title: 'Posts'
      url: '/posts'
      submenu:
        - title: 'By Date'
          url: '/posts'
        - title: 'By Category'
          url: '/categories'

    - title: 'FIRE'
      url: 'https://github.com/markusrothe/FIRE'
    
       
owner:
    name: Markus Rothe
    site: https://www.markusrothe.dev
    email: mr@markusrothe.dev
    avatar: images/avatar.png
    bio: Markus Rothe is a full-time developer since 2015, enthusiastic about all things C++, computer graphics, emacs, clean code & software architecture / -design.
    github: markusrothe

social:
    - title: "github"
      url: "https://github.com/markusrothe"
    
background:

timezone: Europe/Berlin
locale: de_DE    
future: true
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate

# Amount of post to show on home page
paginate: 5

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: dark-post
page_layout: page
# Format titles with titlecase?
titlecase: true


exclude: ["LICENSE"]

